rem Execute from your ODI bin directory.

rem Master Repository Sample.

startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_TECHNOLOGY -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.TechnologyInternalID=12999

startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_DATA_SERVER -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.DataServerInternalID=56000

startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_PHYSICAL_SCHEMA -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.PhysicalSchemaInternalID=1110

startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_CONTEXT -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.ContextInternalID=2010

startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_LOGICAL_SCHEMA -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.LogicalSchemaInternalID=1080

startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_PROJECT -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.ProjectInternalID=3001

rem Work Repository Sample.

startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_MARKER_GROUP -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.GroupMarkerInternalID=61101

startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_FOLDER -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.FolderInternalID=7001

startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_PROCEDURE -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.ProcedureInternalID=325008

rem startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_MODEL_FOLDER -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.ModelFolderInternalID=

startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_MODEL -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.ModelInternalID=6001

startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_DATA_STORE -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.DataStoreInternalID=2038101

startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_RELATIONSHIP -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.RelationshipInternalID=3002

startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_VARIABLE -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.VariableInternalID=137101

startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_SEQUENCE -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.SequenceInternalID=3101

startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_USER_FUNCTION -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.UserFunctionInternalID=1008

startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_INTERFACE -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.InterfaceInternalID=3239101

startcmd.bat OdiStartScen -SCEN_NAME=OSUTL_EXPORT_PACKAGE -SCEN_VERSION=999 -CONTEXT=GLOBAL -OS.PackageInternalID=2783101