call startcmd.bat OdiExportObject -I_OBJECT=0 "-FILE_NAME=C:\Temp\CON_Security Connection.xml" -CLASS_NAME=SnpConnect -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=1999 "-FILE_NAME=C:\Temp\TECH_ORACLE.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=2999 "-FILE_NAME=C:\Temp\CTX_GLOBAL.xml" -CLASS_NAME=SnpContext -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=2999 "-FILE_NAME=C:\Temp\TECH_FILE.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=3999 "-FILE_NAME=C:\Temp\TECH_IBM_DB2_400.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=4999 "-FILE_NAME=C:\Temp\LS_HSQL_DEMO_SRC.xml" -CLASS_NAME=SnpLschema -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=4999 "-FILE_NAME=C:\Temp\TECH_IBM_DB2_UDB.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=5999 "-FILE_NAME=C:\Temp\CON_HSQL_LOCALHOST_20001.xml" -CLASS_NAME=SnpConnect -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=5999 "-FILE_NAME=C:\Temp\LS_HSQL_DEMO_TARG.xml" -CLASS_NAME=SnpLschema -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=5999 "-FILE_NAME=C:\Temp\PS_HSQL_LOCALHOST_20001_Default.xml" -CLASS_NAME=SnpPschema -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=5999 "-FILE_NAME=C:\Temp\TECH_INFORMIX.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=6999 "-FILE_NAME=C:\Temp\CON_HSQL_LOCALHOST_20002.xml" -CLASS_NAME=SnpConnect -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=6999 "-FILE_NAME=C:\Temp\LS_FILE_DEMO_SRC.xml" -CLASS_NAME=SnpLschema -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=6999 "-FILE_NAME=C:\Temp\PS_HSQL_LOCALHOST_20002_Default.xml" -CLASS_NAME=SnpPschema -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=6999 "-FILE_NAME=C:\Temp\TECH_MICROSOFT_SQL_SERVER.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=7999 "-FILE_NAME=C:\Temp\CON_FILE_GENERIC.xml" -CLASS_NAME=SnpConnect -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=7999 "-FILE_NAME=C:\Temp\LS_ SUNOPSIS_MEMORY_ENGINE.xml" -CLASS_NAME=SnpLschema -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=7999 "-FILE_NAME=C:\Temp\PS_FILE_GENERIC____demo_file.xml" -CLASS_NAME=SnpPschema -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=7999 "-FILE_NAME=C:\Temp\TECH_MICROSOFT_ACCESS.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=8999 "-FILE_NAME=C:\Temp\CON_SUNOPSIS_MEMORY_ENGINE.xml" -CLASS_NAME=SnpConnect -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=8999 "-FILE_NAME=C:\Temp\LS_XML_DEMO_GEO.xml" -CLASS_NAME=SnpLschema -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=8999 "-FILE_NAME=C:\Temp\PS_SUNOPSIS_MEMORY_ENGINE_Default.xml" -CLASS_NAME=SnpPschema -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=8999 "-FILE_NAME=C:\Temp\TECH_MICROSOFT_EXCEL.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=9999 "-FILE_NAME=C:\Temp\CON_XML_GEO_DIM.xml" -CLASS_NAME=SnpConnect -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=9999 "-FILE_NAME=C:\Temp\PS_XML_GEO_DIM_GEO.xml" -CLASS_NAME=SnpPschema -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=9999 "-FILE_NAME=C:\Temp\TECH_SYBASE_AS_ANYWHERE.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=10999 "-FILE_NAME=C:\Temp\TECH_SYBASE_AS_ENTERPRISE.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=11999 "-FILE_NAME=C:\Temp\TECH_SYBASE_AS_IQ.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=12999 "-FILE_NAME=C:\Temp\TECH_TERADATA.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=13999 "-FILE_NAME=C:\Temp\TECH_INGRES.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=14999 "-FILE_NAME=C:\Temp\TECH_INTERBASE.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=15000 "-FILE_NAME=C:\Temp\CON_WORKREP.xml" -CLASS_NAME=SnpConnect -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=15999 "-FILE_NAME=C:\Temp\TECH_DBASE.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=16999 "-FILE_NAME=C:\Temp\TECH_BTRIEVE.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=17999 "-FILE_NAME=C:\Temp\TECH_MYSQL.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=18999 "-FILE_NAME=C:\Temp\TECH_PARADOX.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=19999 "-FILE_NAME=C:\Temp\TECH_PROGRESS.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=20999 "-FILE_NAME=C:\Temp\TECH_UNIVERSE.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=21999 "-FILE_NAME=C:\Temp\TECH_OPERATING_SYSTEM.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=22999 "-FILE_NAME=C:\Temp\TECH_SUNOPSIS_API.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=23999 "-FILE_NAME=C:\Temp\TECH_HYPERSONIC_SQL.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=24999 "-FILE_NAME=C:\Temp\TECH_JMSTOPIC.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=25999 "-FILE_NAME=C:\Temp\TECH_JMSQUEUE.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=26999 "-FILE_NAME=C:\Temp\TECH_SUNOPSIS_ENGINE.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=27999 "-FILE_NAME=C:\Temp\TECH_XML.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=30999 "-FILE_NAME=C:\Temp\TECH_BEANSHELL.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=32999 "-FILE_NAME=C:\Temp\TECH_JAVASCRIPT.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=33999 "-FILE_NAME=C:\Temp\TECH_JYTHON.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=34999 "-FILE_NAME=C:\Temp\TECH_NETREXX.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=37999 "-FILE_NAME=C:\Temp\TECH_SAPJCO.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=38999 "-FILE_NAME=C:\Temp\TECH_GENERIC_SQL.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=39999 "-FILE_NAME=C:\Temp\TECH_POSTGRESSQL.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=40999 "-FILE_NAME=C:\Temp\TECH_JMS_TOPIC_XML.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=41999 "-FILE_NAME=C:\Temp\TECH_JMS_QUEUE_XML.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=42999 "-FILE_NAME=C:\Temp\TECH_LDAP.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=43999 "-FILE_NAME=C:\Temp\TECH_HYPERION_ESSBASE.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=44999 "-FILE_NAME=C:\Temp\TECH_NETEZZA.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
call startcmd.bat OdiExportObject -I_OBJECT=46000 "-FILE_NAME=C:\Temp\TECH_AXIS2.xml" -CLASS_NAME=SnpTechno -FORCE_OVERWRITE=yes -RECURSIVE_EXPORT=yes
