

REM SWIFT_MOI/CONTACTS
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=128101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=7001 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/CLAIMS
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=126101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/COMMON
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=125101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/COMPLAINTS
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=127101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/CUSTOMERS
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=129101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/DOCUMENTS
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=131101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/FRD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=3008 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/FRD_MM
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=5008 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/INTERMEDIARIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=132101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/JIGSAW_CALL_TO_CONTACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=4007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/MARKETING
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=134101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/MEDICAL_CODES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=133101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/PARTIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=124101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/PORTFOLIOS
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=135101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/PRE_AUTHS
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=136101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/PRICING
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=138101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/PRODUCTS
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=137101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/PROVIDERS
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=139101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/UTILITIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=8001 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/QUOTES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=140101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/SCHEDULE_BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=9001 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/SCHEDULE_LOAD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=145101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/SWIFT_FINANCE
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=130101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/SYSTEM_USERS
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=141101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/TASKS
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=142101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SWIFT_MOI/REFERENCE_DATA
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3001 -FOLDER=121101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM ODI_UPGRADE/Teradata To Teradata
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1031 -FOLDER=6031 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM ODI_UPGRADE/Teradata to Oracle
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1031 -FOLDER=5031 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM ODI_UPGRADE/MSSQL 2005 to Teradata
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1031 -FOLDER=8031 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM ODI_UPGRADE/Teradata to MSSQL2005
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1031 -FOLDER=9031 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM ODI_UPGRADE/Oracle to MSSQL2008
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1031 -FOLDER=10031 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM ODI_UPGRADE/MSSQL2008 to Teradata
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1031 -FOLDER=11031 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM ODI_UPGRADE/MSSQL2008 to MSSQL2008
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1031 -FOLDER=12031 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM ODI_UPGRADE/File to Teradata
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1031 -FOLDER=13031 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM ODI_UPGRADE/MSSQL2008 To File
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1031 -FOLDER=14031 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM ODI_UPGRADE/Oracle To Teradata
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1031 -FOLDER=4031 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM EM/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=17101 -FOLDER=87101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM EM/EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=17101 -FOLDER=86101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM EM/SCHEDULE_BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=17101 -FOLDER=88101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM EM/SCHEDULE_EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=17101 -FOLDER=89101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM EM/UTILITIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=17101 -FOLDER=90101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MI/EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=5007 -FOLDER=12007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MI/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=5007 -FOLDER=15007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MI/SCHEDULE_EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=5007 -FOLDER=16007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MI/SCHEDULE_BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=5007 -FOLDER=17007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MI/UTILITIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=5007 -FOLDER=18007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM IM/UTILITIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=13101 -FOLDER=68101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM IM/SCHEDULE_EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=13101 -FOLDER=65101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM IM/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=13101 -FOLDER=62101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM IM/SCHEDULE_BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=13101 -FOLDER=63101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM IM/EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=13101 -FOLDER=64101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MD/SCHEDULE_BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=4007 -FOLDER=19007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MD/UTILITIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=4007 -FOLDER=20007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MD/EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=4007 -FOLDER=8007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MD/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=4007 -FOLDER=10007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MD/SCHEDULE_EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=4007 -FOLDER=11007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM GM/UTILITIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=10101 -FOLDER=67101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM GM/SCHEDULE_EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=10101 -FOLDER=51101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM GM/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=10101 -FOLDER=49101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM GM/EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=10101 -FOLDER=50101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM GM/SCHEDULE_BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=10101 -FOLDER=52101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM DM/UTILITIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=8021 -FOLDER=14021 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM DM/SCHEDULE_EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=8021 -FOLDER=15021 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM DM/EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=8021 -FOLDER=11021 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM DM/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=8021 -FOLDER=27021 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MC/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1010 -FOLDER=28010 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MC/EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1010 -FOLDER=29010 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MC/SCHEDULE_BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1010 -FOLDER=32010 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MC/SCHEDULE_EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1010 -FOLDER=33010 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MC/UTILITIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1010 -FOLDER=72101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM ME/UTILITIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=4101 -FOLDER=73101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM ME/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=4101 -FOLDER=14101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM ME/EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=4101 -FOLDER=15101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM ME/SCHEDULE_BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=4101 -FOLDER=18101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM ME/SCHEDULE_EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=4101 -FOLDER=17101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MM/UTILITIES-to-delete
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1021 -FOLDER=19021 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MM/EXTRACTS
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1021 -FOLDER=1021 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MM/SCHEDULE_EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=1021 -FOLDER=22021 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MU/UTILITIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=16101 -FOLDER=161101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MU/SCHEDULE_EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=16101 -FOLDER=107101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MU/SCHEDULE_BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=16101 -FOLDER=105101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MU/EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=16101 -FOLDER=106101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MU/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=16101 -FOLDER=83101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM OT/SCHEDULE_EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=2021 -FOLDER=3021 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM OT/EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=2021 -FOLDER=2021 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM OT/UTILITIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=2021 -FOLDER=34007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM OT/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=2021 -FOLDER=16021 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM OT/SCHEDULE_BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=2021 -FOLDER=21021 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM UKM_PEOPLESOFT_MOI/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3101 -FOLDER=9101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM UKM_PEOPLESOFT_MOI/EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3101 -FOLDER=10101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM UKM_PEOPLESOFT_MOI/SCHEDULE_BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3101 -FOLDER=11101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM UKM_PEOPLESOFT_MOI/SCHEDULE_EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3101 -FOLDER=12101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM PSW/EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=11101 -FOLDER=54101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM PSW/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=11101 -FOLDER=53101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM PSW/SCHEDULE_BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=11101 -FOLDER=55101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM PSW/SCHEDULE_EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=11101 -FOLDER=56101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MP/UTILITIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=6007 -FOLDER=13007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MP/SCHEDULE_EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=6007 -FOLDER=22007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MP/EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=6007 -FOLDER=24007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MP/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=6007 -FOLDER=29007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM OM/EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=8101 -FOLDER=40101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM OM/SCHEDULE_EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=8101 -FOLDER=41101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM OM/SCHEDULE_BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=8101 -FOLDER=47101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM OM/UTILITIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=8101 -FOLDER=42101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM OM/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=8101 -FOLDER=46101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MR/EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=7007 -FOLDER=14007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MR/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=7007 -FOLDER=25007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MR/SCHEDULE_EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=7007 -FOLDER=26007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MR/SCHEDULE_BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=7007 -FOLDER=27007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MR/UTILITIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=7007 -FOLDER=28007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM RM/EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=36101 -FOLDER=155101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM RM/SCHEDULE_EXTRACT
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=36101 -FOLDER=156101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM RM/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=36101 -FOLDER=157101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM RM/SCHEDULE_BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=36101 -FOLDER=158101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM RM/UTILITIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=36101 -FOLDER=159101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SM/SCHEDULE_EXTRACTS
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3007 -FOLDER=5007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM SM/EXTRACTS
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=3007 -FOLDER=7007 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MOI_RECONCILATION/UTILITIES
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=35101 -FOLDER=2031 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES

REM MOI_RECONCILATION/BUILD
cd /d C:\ODI\$DBCONNREF_oracledi_10.1.3.4.2\oracledi\bin
call startcmd.bat OdiGenerateAllScen -PROJECT=35101 -FOLDER=153101 -MODE=CREATE -GRPMARKER=MOI_CODE_RECONCILLIATION -MARKER=MOI_CODE_RECONCILLIATION -GENERATE_PACK=YES -GENERATE_POP=YES -GENERATE_TRT=YES -GENERATE_VAR=YES