CREATE USER odirepofordemo IDENTIFIED BY odirepofordemo DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp
/

CREATE USER odirepofordemo2 IDENTIFIED BY odirepofordemo2 DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp
/

GRANT CONNECT, RESOURCE, CREATE DATABASE LINK TO odirepofordemo
/

GRANT CONNECT, RESOURCE, CREATE DATABASE LINK TO odirepofordemo2
/